kind: Service
apiVersion: v1
metadata:
  name: cfdrelloapi
  namespace: trainee
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30355
  type: NodePort
  selector:
    app: trainee