apiVersion: v1
kind: Service
metadata:
  name: cfdrelloapi
  namespace: trainee
spec:
  selector:
    app: cfdrelloapi
  type: NodePort
  ports:
  - name: cfdrelloapi
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30355